--RAISE THE 15600 ERROR
RAISERROR (15600, -1, -1, 'mysp_CreateCustomer');

-- SAMPLE QUERY THAT WILL RAISE AN ERROR IF GITHUB_USERNAMES ARE NULLED.
IF EXISTS (SELECT * FROM HRIS_CLEANED WHERE GITHUB_USERNAME IS NULL)
BEGIN
    RAISERROR('Error: Column GITHUB_USERNAME contains NULL values.', 16, 1);
END

-- VIEW THE ALERT LOGGING TABLE
SELECT * FROM [PS_AUTOMATING_DATA_CLEANSING].[dbo].[ALERT_LOGGING]

-- MAKE SURE THAT YOU USE THE "WITH LOG" OPTION TO TRIGGER THE ALERT AND RESPONSE JOB SUCCESSFULLY.
IF EXISTS (SELECT * FROM HRIS_CLEANED WHERE GITHUB_USERNAME IS NULL)
BEGIN
    RAISERROR('Error: Column GITHUB_USERNAME contains NULL values.', 16, 1) WITH LOG;
END

-- VIEW THE ALERT LOGGING TABLE
SELECT * FROM [PS_AUTOMATING_DATA_CLEANSING].[dbo].[ALERT_LOGGING]


-- EXAMPLE TESTING THE TEXT FILTER.
IF EXISTS (SELECT * FROM HRIS_CLEANED WHERE GITHUB_USERNAME IS NULL)
BEGIN
    RAISERROR('Error: Column X contains NULL values.', 16, 1) WITH LOG;
END

-- VIEW THE ALERT LOGGING TABLE
SELECT * FROM [PS_AUTOMATING_DATA_CLEANSING].[dbo].[ALERT_LOGGING]

/*
-- NOTE YOU CAN ALSO VIEW THE SQL SERVER LOG FOR RAISE ERRORS AND THE CUSTOM ERROR ID WITH THE FOLLOWING QUERY:

DROP TABLE IF EXISTS #TEMP_LOG
CREATE TABLE #TEMP_LOG
(
LogDate datetime,
ProcessInfo VARCHAR(MAX),
TEXT VARCHAR(MAX)
)

INSERT INTO #TEMP_LOG
EXEC xp_readerrorlog;

SELECT * FROM #TEMP_LOG WHERE TEXT LIKE '%ERROR: 50000%'

*/
