USE PS_AUTOMATING_DATA_CLEANSING;

--CREATE A STORED PROCEDURE STATEMENT
CREATE PROC SPX_BASIC @NAME VARCHAR(20)
AS
BEGIN
PRINT('Hello ' + @NAME)
END

EXEC SPX_BASIC 'Pluralsight'

--ALTER A STORED PROCEDURE STATEMENT
ALTER PROC SPX_BASIC @NAME VARCHAR(20)
AS
BEGIN
PRINT('Goodbye ' + @NAME)
END

EXEC SPX_BASIC 'Pluralsight'

--DROP A STORED PROCEDURE STATEMENT
DROP PROC SPX_BASIC